SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

SHOW WARNINGS;
DROP SCHEMA IF EXISTS `cms` ;
CREATE SCHEMA IF NOT EXISTS `cms` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
SHOW WARNINGS;
DROP SCHEMA IF EXISTS `information_schema` ;
CREATE SCHEMA IF NOT EXISTS `information_schema` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
DROP SCHEMA IF EXISTS `mysql` ;
CREATE SCHEMA IF NOT EXISTS `mysql` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
SHOW WARNINGS;
USE `cms` ;

-- -----------------------------------------------------
-- Table `cms`.`departmentinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`departmentinfo` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `cms`.`departmentinfo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `departmentcode` INT(11) NOT NULL COMMENT 'NONE USE' ,
  `departmentname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cms`.`jobinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`jobinfo` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `cms`.`jobinfo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `jobname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL ,
  `projectcode` INT(11) NULL DEFAULT NULL ,
  `pubdate` DATE NOT NULL ,
  `department` INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cms`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`menu` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `cms`.`menu` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `menuname` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL ,
  `menulink` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL ,
  `parentmenuid` INT(11) NULL DEFAULT NULL ,
  `updip` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `upduser` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `updtime` TIMESTAMP NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = MyISAM
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cms`.`personinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`personinfo` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `cms`.`personinfo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `chnname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `engname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `phonenum` INT(20) NULL DEFAULT NULL ,
  `workexpr` INT(11) NULL DEFAULT NULL ,
  `university` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `degree` INT(11) NULL DEFAULT NULL ,
  `workingcom` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `langskill` INT(11) NULL DEFAULT '0' ,
  `sdskill` INT(11) NULL DEFAULT '0' ,
  `techskill` INT(11) NULL DEFAULT '0' ,
  `stability` INT(11) NULL DEFAULT '0' ,
  `workhistory` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `comments` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `lang` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cms`.`resumeinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`resumeinfo` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `cms`.`resumeinfo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `jobid` INT(11) NOT NULL ,
  `personid` INT(11) NOT NULL ,
  `gotdate` DATE NULL DEFAULT NULL ,
  `screendate` DATE NULL DEFAULT NULL ,
  `screener` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `source` INT(11) NULL DEFAULT NULL ,
  `referraler` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `viewdate` DATE NULL DEFAULT NULL ,
  `viewer` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `viewresult` INT(11) NULL DEFAULT NULL ,
  `remark` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cms`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`test` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `cms`.`test` (
  `idtest` INT(11) NOT NULL ,
  `num` DECIMAL(10,0) NULL DEFAULT NULL ,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  PRIMARY KEY (`idtest`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cms`.`userinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`userinfo` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `cms`.`userinfo` (
  `id` INT(10) NOT NULL AUTO_INCREMENT ,
  `username` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL ,
  `userpass` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL ,
  `authcode` TINYINT(4) NOT NULL ,
  `updip` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `upduser` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `updtime` TIMESTAMP NULL DEFAULT NULL ,
  `projectcode` INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (`id`, `username`) )
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
USE `information_schema` ;

-- -----------------------------------------------------
-- Table `information_schema`.`CHARACTER_SETS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`CHARACTER_SETS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`CHARACTER_SETS` (
  `CHARACTER_SET_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `DEFAULT_COLLATE_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `DESCRIPTION` VARCHAR(60) NOT NULL DEFAULT '' ,
  `MAXLEN` BIGINT(3) NOT NULL DEFAULT '0' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`COLLATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`COLLATIONS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`COLLATIONS` (
  `COLLATION_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `CHARACTER_SET_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `ID` BIGINT(11) NOT NULL DEFAULT '0' ,
  `IS_DEFAULT` VARCHAR(3) NOT NULL DEFAULT '' ,
  `IS_COMPILED` VARCHAR(3) NOT NULL DEFAULT '' ,
  `SORTLEN` BIGINT(3) NOT NULL DEFAULT '0' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`COLLATION_CHARACTER_SET_APPLICABILITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`COLLATION_CHARACTER_SET_APPLICABILITY` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`COLLATION_CHARACTER_SET_APPLICABILITY` (
  `COLLATION_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `CHARACTER_SET_NAME` VARCHAR(32) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`COLUMNS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`COLUMNS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`COLUMNS` (
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `COLUMN_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ORDINAL_POSITION` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0' ,
  `COLUMN_DEFAULT` LONGTEXT NULL DEFAULT NULL ,
  `IS_NULLABLE` VARCHAR(3) NOT NULL DEFAULT '' ,
  `DATA_TYPE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `CHARACTER_MAXIMUM_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `CHARACTER_OCTET_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `NUMERIC_PRECISION` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `NUMERIC_SCALE` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `CHARACTER_SET_NAME` VARCHAR(32) NULL DEFAULT NULL ,
  `COLLATION_NAME` VARCHAR(32) NULL DEFAULT NULL ,
  `COLUMN_TYPE` LONGTEXT NOT NULL ,
  `COLUMN_KEY` VARCHAR(3) NOT NULL DEFAULT '' ,
  `EXTRA` VARCHAR(27) NOT NULL DEFAULT '' ,
  `PRIVILEGES` VARCHAR(80) NOT NULL DEFAULT '' ,
  `COLUMN_COMMENT` VARCHAR(255) NOT NULL DEFAULT '' )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`COLUMN_PRIVILEGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`COLUMN_PRIVILEGES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`COLUMN_PRIVILEGES` (
  `GRANTEE` VARCHAR(81) NOT NULL DEFAULT '' ,
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `COLUMN_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `PRIVILEGE_TYPE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `IS_GRANTABLE` VARCHAR(3) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`ENGINES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`ENGINES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`ENGINES` (
  `ENGINE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `SUPPORT` VARCHAR(8) NOT NULL DEFAULT '' ,
  `COMMENT` VARCHAR(80) NOT NULL DEFAULT '' ,
  `TRANSACTIONS` VARCHAR(3) NULL DEFAULT NULL ,
  `XA` VARCHAR(3) NULL DEFAULT NULL ,
  `SAVEPOINTS` VARCHAR(3) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`EVENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`EVENTS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`EVENTS` (
  `EVENT_CATALOG` VARCHAR(64) NULL DEFAULT NULL ,
  `EVENT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `EVENT_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `DEFINER` VARCHAR(77) NOT NULL DEFAULT '' ,
  `TIME_ZONE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `EVENT_BODY` VARCHAR(8) NOT NULL DEFAULT '' ,
  `EVENT_DEFINITION` LONGTEXT NOT NULL ,
  `EVENT_TYPE` VARCHAR(9) NOT NULL DEFAULT '' ,
  `EXECUTE_AT` DATETIME NULL DEFAULT NULL ,
  `INTERVAL_VALUE` VARCHAR(256) NULL DEFAULT NULL ,
  `INTERVAL_FIELD` VARCHAR(18) NULL DEFAULT NULL ,
  `SQL_MODE` VARCHAR(8192) NOT NULL DEFAULT '' ,
  `STARTS` DATETIME NULL DEFAULT NULL ,
  `ENDS` DATETIME NULL DEFAULT NULL ,
  `STATUS` VARCHAR(18) NOT NULL DEFAULT '' ,
  `ON_COMPLETION` VARCHAR(12) NOT NULL DEFAULT '' ,
  `CREATED` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `LAST_ALTERED` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `LAST_EXECUTED` DATETIME NULL DEFAULT NULL ,
  `EVENT_COMMENT` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ORIGINATOR` BIGINT(10) NOT NULL DEFAULT '0' ,
  `CHARACTER_SET_CLIENT` VARCHAR(32) NOT NULL DEFAULT '' ,
  `COLLATION_CONNECTION` VARCHAR(32) NOT NULL DEFAULT '' ,
  `DATABASE_COLLATION` VARCHAR(32) NOT NULL DEFAULT '' )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`FILES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`FILES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`FILES` (
  `FILE_ID` BIGINT(4) NOT NULL DEFAULT '0' ,
  `FILE_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `FILE_TYPE` VARCHAR(20) NOT NULL DEFAULT '' ,
  `TABLESPACE_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `TABLE_CATALOG` VARCHAR(64) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NULL DEFAULT NULL ,
  `TABLE_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `LOGFILE_GROUP_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `LOGFILE_GROUP_NUMBER` BIGINT(4) NULL DEFAULT NULL ,
  `ENGINE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `FULLTEXT_KEYS` VARCHAR(64) NULL DEFAULT NULL ,
  `DELETED_ROWS` BIGINT(4) NULL DEFAULT NULL ,
  `UPDATE_COUNT` BIGINT(4) NULL DEFAULT NULL ,
  `FREE_EXTENTS` BIGINT(4) NULL DEFAULT NULL ,
  `TOTAL_EXTENTS` BIGINT(4) NULL DEFAULT NULL ,
  `EXTENT_SIZE` BIGINT(4) NOT NULL DEFAULT '0' ,
  `INITIAL_SIZE` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `MAXIMUM_SIZE` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `AUTOEXTEND_SIZE` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `CREATION_TIME` DATETIME NULL DEFAULT NULL ,
  `LAST_UPDATE_TIME` DATETIME NULL DEFAULT NULL ,
  `LAST_ACCESS_TIME` DATETIME NULL DEFAULT NULL ,
  `RECOVER_TIME` BIGINT(4) NULL DEFAULT NULL ,
  `TRANSACTION_COUNTER` BIGINT(4) NULL DEFAULT NULL ,
  `VERSION` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `ROW_FORMAT` VARCHAR(10) NULL DEFAULT NULL ,
  `TABLE_ROWS` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `AVG_ROW_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `MAX_DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `INDEX_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `DATA_FREE` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `CREATE_TIME` DATETIME NULL DEFAULT NULL ,
  `UPDATE_TIME` DATETIME NULL DEFAULT NULL ,
  `CHECK_TIME` DATETIME NULL DEFAULT NULL ,
  `CHECKSUM` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `STATUS` VARCHAR(20) NOT NULL DEFAULT '' ,
  `EXTRA` VARCHAR(255) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`GLOBAL_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`GLOBAL_STATUS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`GLOBAL_STATUS` (
  `VARIABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `VARIABLE_VALUE` VARCHAR(1024) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`GLOBAL_VARIABLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`GLOBAL_VARIABLES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`GLOBAL_VARIABLES` (
  `VARIABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `VARIABLE_VALUE` VARCHAR(1024) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`KEY_COLUMN_USAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`KEY_COLUMN_USAGE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`KEY_COLUMN_USAGE` (
  `CONSTRAINT_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `CONSTRAINT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `CONSTRAINT_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `COLUMN_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ORDINAL_POSITION` BIGINT(10) NOT NULL DEFAULT '0' ,
  `POSITION_IN_UNIQUE_CONSTRAINT` BIGINT(10) NULL DEFAULT NULL ,
  `REFERENCED_TABLE_SCHEMA` VARCHAR(64) NULL DEFAULT NULL ,
  `REFERENCED_TABLE_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `REFERENCED_COLUMN_NAME` VARCHAR(64) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`PARTITIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`PARTITIONS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`PARTITIONS` (
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `PARTITION_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `SUBPARTITION_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `PARTITION_ORDINAL_POSITION` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `SUBPARTITION_ORDINAL_POSITION` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `PARTITION_METHOD` VARCHAR(12) NULL DEFAULT NULL ,
  `SUBPARTITION_METHOD` VARCHAR(12) NULL DEFAULT NULL ,
  `PARTITION_EXPRESSION` LONGTEXT NULL DEFAULT NULL ,
  `SUBPARTITION_EXPRESSION` LONGTEXT NULL DEFAULT NULL ,
  `PARTITION_DESCRIPTION` LONGTEXT NULL DEFAULT NULL ,
  `TABLE_ROWS` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0' ,
  `AVG_ROW_LENGTH` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0' ,
  `DATA_LENGTH` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0' ,
  `MAX_DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `INDEX_LENGTH` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0' ,
  `DATA_FREE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0' ,
  `CREATE_TIME` DATETIME NULL DEFAULT NULL ,
  `UPDATE_TIME` DATETIME NULL DEFAULT NULL ,
  `CHECK_TIME` DATETIME NULL DEFAULT NULL ,
  `CHECKSUM` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `PARTITION_COMMENT` VARCHAR(80) NOT NULL DEFAULT '' ,
  `NODEGROUP` VARCHAR(12) NOT NULL DEFAULT '' ,
  `TABLESPACE_NAME` VARCHAR(64) NULL DEFAULT NULL )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`PLUGINS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`PLUGINS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`PLUGINS` (
  `PLUGIN_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `PLUGIN_VERSION` VARCHAR(20) NOT NULL DEFAULT '' ,
  `PLUGIN_STATUS` VARCHAR(10) NOT NULL DEFAULT '' ,
  `PLUGIN_TYPE` VARCHAR(80) NOT NULL DEFAULT '' ,
  `PLUGIN_TYPE_VERSION` VARCHAR(20) NOT NULL DEFAULT '' ,
  `PLUGIN_LIBRARY` VARCHAR(64) NULL DEFAULT NULL ,
  `PLUGIN_LIBRARY_VERSION` VARCHAR(20) NULL DEFAULT NULL ,
  `PLUGIN_AUTHOR` VARCHAR(64) NULL DEFAULT NULL ,
  `PLUGIN_DESCRIPTION` LONGTEXT NULL DEFAULT NULL ,
  `PLUGIN_LICENSE` VARCHAR(80) NULL DEFAULT NULL )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`PROCESSLIST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`PROCESSLIST` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`PROCESSLIST` (
  `ID` BIGINT(4) NOT NULL DEFAULT '0' ,
  `USER` VARCHAR(16) NOT NULL DEFAULT '' ,
  `HOST` VARCHAR(64) NOT NULL DEFAULT '' ,
  `DB` VARCHAR(64) NULL DEFAULT NULL ,
  `COMMAND` VARCHAR(16) NOT NULL DEFAULT '' ,
  `TIME` INT(7) NOT NULL DEFAULT '0' ,
  `STATE` VARCHAR(64) NULL DEFAULT NULL ,
  `INFO` LONGTEXT NULL DEFAULT NULL )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`PROFILING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`PROFILING` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`PROFILING` (
  `QUERY_ID` INT(20) NOT NULL DEFAULT '0' ,
  `SEQ` INT(20) NOT NULL DEFAULT '0' ,
  `STATE` VARCHAR(30) NOT NULL DEFAULT '' ,
  `DURATION` DECIMAL(9,6) NOT NULL DEFAULT '0.000000' ,
  `CPU_USER` DECIMAL(9,6) NULL DEFAULT NULL ,
  `CPU_SYSTEM` DECIMAL(9,6) NULL DEFAULT NULL ,
  `CONTEXT_VOLUNTARY` INT(20) NULL DEFAULT NULL ,
  `CONTEXT_INVOLUNTARY` INT(20) NULL DEFAULT NULL ,
  `BLOCK_OPS_IN` INT(20) NULL DEFAULT NULL ,
  `BLOCK_OPS_OUT` INT(20) NULL DEFAULT NULL ,
  `MESSAGES_SENT` INT(20) NULL DEFAULT NULL ,
  `MESSAGES_RECEIVED` INT(20) NULL DEFAULT NULL ,
  `PAGE_FAULTS_MAJOR` INT(20) NULL DEFAULT NULL ,
  `PAGE_FAULTS_MINOR` INT(20) NULL DEFAULT NULL ,
  `SWAPS` INT(20) NULL DEFAULT NULL ,
  `SOURCE_FUNCTION` VARCHAR(30) NULL DEFAULT NULL ,
  `SOURCE_FILE` VARCHAR(20) NULL DEFAULT NULL ,
  `SOURCE_LINE` INT(20) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`REFERENTIAL_CONSTRAINTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`REFERENTIAL_CONSTRAINTS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`REFERENTIAL_CONSTRAINTS` (
  `CONSTRAINT_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `CONSTRAINT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `CONSTRAINT_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `UNIQUE_CONSTRAINT_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `UNIQUE_CONSTRAINT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `UNIQUE_CONSTRAINT_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `MATCH_OPTION` VARCHAR(64) NOT NULL DEFAULT '' ,
  `UPDATE_RULE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `DELETE_RULE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `REFERENCED_TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`ROUTINES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`ROUTINES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`ROUTINES` (
  `SPECIFIC_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ROUTINE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `ROUTINE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ROUTINE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ROUTINE_TYPE` VARCHAR(9) NOT NULL DEFAULT '' ,
  `DTD_IDENTIFIER` VARCHAR(64) NULL DEFAULT NULL ,
  `ROUTINE_BODY` VARCHAR(8) NOT NULL DEFAULT '' ,
  `ROUTINE_DEFINITION` LONGTEXT NULL DEFAULT NULL ,
  `EXTERNAL_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `EXTERNAL_LANGUAGE` VARCHAR(64) NULL DEFAULT NULL ,
  `PARAMETER_STYLE` VARCHAR(8) NOT NULL DEFAULT '' ,
  `IS_DETERMINISTIC` VARCHAR(3) NOT NULL DEFAULT '' ,
  `SQL_DATA_ACCESS` VARCHAR(64) NOT NULL DEFAULT '' ,
  `SQL_PATH` VARCHAR(64) NULL DEFAULT NULL ,
  `SECURITY_TYPE` VARCHAR(7) NOT NULL DEFAULT '' ,
  `CREATED` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `LAST_ALTERED` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `SQL_MODE` VARCHAR(8192) NOT NULL DEFAULT '' ,
  `ROUTINE_COMMENT` VARCHAR(64) NOT NULL DEFAULT '' ,
  `DEFINER` VARCHAR(77) NOT NULL DEFAULT '' ,
  `CHARACTER_SET_CLIENT` VARCHAR(32) NOT NULL DEFAULT '' ,
  `COLLATION_CONNECTION` VARCHAR(32) NOT NULL DEFAULT '' ,
  `DATABASE_COLLATION` VARCHAR(32) NOT NULL DEFAULT '' )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`SCHEMATA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`SCHEMATA` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`SCHEMATA` (
  `CATALOG_NAME` VARCHAR(512) NULL DEFAULT NULL ,
  `SCHEMA_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `DEFAULT_CHARACTER_SET_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `DEFAULT_COLLATION_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `SQL_PATH` VARCHAR(512) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`SCHEMA_PRIVILEGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`SCHEMA_PRIVILEGES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`SCHEMA_PRIVILEGES` (
  `GRANTEE` VARCHAR(81) NOT NULL DEFAULT '' ,
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `PRIVILEGE_TYPE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `IS_GRANTABLE` VARCHAR(3) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`SESSION_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`SESSION_STATUS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`SESSION_STATUS` (
  `VARIABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `VARIABLE_VALUE` VARCHAR(1024) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`SESSION_VARIABLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`SESSION_VARIABLES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`SESSION_VARIABLES` (
  `VARIABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `VARIABLE_VALUE` VARCHAR(1024) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`STATISTICS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`STATISTICS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`STATISTICS` (
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `NON_UNIQUE` BIGINT(1) NOT NULL DEFAULT '0' ,
  `INDEX_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `INDEX_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `SEQ_IN_INDEX` BIGINT(2) NOT NULL DEFAULT '0' ,
  `COLUMN_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `COLLATION` VARCHAR(1) NULL DEFAULT NULL ,
  `CARDINALITY` BIGINT(21) NULL DEFAULT NULL ,
  `SUB_PART` BIGINT(3) NULL DEFAULT NULL ,
  `PACKED` VARCHAR(10) NULL DEFAULT NULL ,
  `NULLABLE` VARCHAR(3) NOT NULL DEFAULT '' ,
  `INDEX_TYPE` VARCHAR(16) NOT NULL DEFAULT '' ,
  `COMMENT` VARCHAR(16) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`TABLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`TABLES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`TABLES` (
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_TYPE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ENGINE` VARCHAR(64) NULL DEFAULT NULL ,
  `VERSION` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `ROW_FORMAT` VARCHAR(10) NULL DEFAULT NULL ,
  `TABLE_ROWS` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `AVG_ROW_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `MAX_DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `INDEX_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `DATA_FREE` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `AUTO_INCREMENT` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `CREATE_TIME` DATETIME NULL DEFAULT NULL ,
  `UPDATE_TIME` DATETIME NULL DEFAULT NULL ,
  `CHECK_TIME` DATETIME NULL DEFAULT NULL ,
  `TABLE_COLLATION` VARCHAR(32) NULL DEFAULT NULL ,
  `CHECKSUM` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `CREATE_OPTIONS` VARCHAR(255) NULL DEFAULT NULL ,
  `TABLE_COMMENT` VARCHAR(80) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`TABLE_CONSTRAINTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`TABLE_CONSTRAINTS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`TABLE_CONSTRAINTS` (
  `CONSTRAINT_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `CONSTRAINT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `CONSTRAINT_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `CONSTRAINT_TYPE` VARCHAR(64) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`TABLE_PRIVILEGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`TABLE_PRIVILEGES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`TABLE_PRIVILEGES` (
  `GRANTEE` VARCHAR(81) NOT NULL DEFAULT '' ,
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `PRIVILEGE_TYPE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `IS_GRANTABLE` VARCHAR(3) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`TRIGGERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`TRIGGERS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`TRIGGERS` (
  `TRIGGER_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TRIGGER_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TRIGGER_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `EVENT_MANIPULATION` VARCHAR(6) NOT NULL DEFAULT '' ,
  `EVENT_OBJECT_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `EVENT_OBJECT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `EVENT_OBJECT_TABLE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ACTION_ORDER` BIGINT(4) NOT NULL DEFAULT '0' ,
  `ACTION_CONDITION` LONGTEXT NULL DEFAULT NULL ,
  `ACTION_STATEMENT` LONGTEXT NOT NULL ,
  `ACTION_ORIENTATION` VARCHAR(9) NOT NULL DEFAULT '' ,
  `ACTION_TIMING` VARCHAR(6) NOT NULL DEFAULT '' ,
  `ACTION_REFERENCE_OLD_TABLE` VARCHAR(64) NULL DEFAULT NULL ,
  `ACTION_REFERENCE_NEW_TABLE` VARCHAR(64) NULL DEFAULT NULL ,
  `ACTION_REFERENCE_OLD_ROW` VARCHAR(3) NOT NULL DEFAULT '' ,
  `ACTION_REFERENCE_NEW_ROW` VARCHAR(3) NOT NULL DEFAULT '' ,
  `CREATED` DATETIME NULL DEFAULT NULL ,
  `SQL_MODE` VARCHAR(8192) NOT NULL DEFAULT '' ,
  `DEFINER` VARCHAR(77) NOT NULL DEFAULT '' ,
  `CHARACTER_SET_CLIENT` VARCHAR(32) NOT NULL DEFAULT '' ,
  `COLLATION_CONNECTION` VARCHAR(32) NOT NULL DEFAULT '' ,
  `DATABASE_COLLATION` VARCHAR(32) NOT NULL DEFAULT '' )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`USER_PRIVILEGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`USER_PRIVILEGES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`USER_PRIVILEGES` (
  `GRANTEE` VARCHAR(81) NOT NULL DEFAULT '' ,
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `PRIVILEGE_TYPE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `IS_GRANTABLE` VARCHAR(3) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `information_schema`.`VIEWS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information_schema`.`VIEWS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `information_schema`.`VIEWS` (
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `VIEW_DEFINITION` LONGTEXT NOT NULL ,
  `CHECK_OPTION` VARCHAR(8) NOT NULL DEFAULT '' ,
  `IS_UPDATABLE` VARCHAR(3) NOT NULL DEFAULT '' ,
  `DEFINER` VARCHAR(77) NOT NULL DEFAULT '' ,
  `SECURITY_TYPE` VARCHAR(7) NOT NULL DEFAULT '' ,
  `CHARACTER_SET_CLIENT` VARCHAR(32) NOT NULL DEFAULT '' ,
  `COLLATION_CONNECTION` VARCHAR(32) NOT NULL DEFAULT '' )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
USE `mysql` ;

-- -----------------------------------------------------
-- Table `mysql`.`columns_priv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`columns_priv` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`columns_priv` (
  `Host` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `User` CHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Table_name` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Column_name` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  `Column_priv` SET('Select','Insert','Update','References') NOT NULL DEFAULT '' ,
  PRIMARY KEY (`Host`, `Db`, `User`, `Table_name`, `Column_name`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Column privileges';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`db`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`db` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`db` (
  `Host` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `User` CHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Select_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Insert_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Update_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Delete_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Drop_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Grant_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `References_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Index_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Alter_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_tmp_table_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Lock_tables_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_view_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Show_view_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_routine_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Alter_routine_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Execute_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Event_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Trigger_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  PRIMARY KEY (`Host`, `Db`, `User`) ,
  INDEX `User` (`User` ASC) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Database privileges';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`event` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`event` (
  `db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `name` CHAR(64) NOT NULL DEFAULT '' ,
  `body` LONGBLOB NOT NULL ,
  `definer` CHAR(77) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `execute_at` DATETIME NULL DEFAULT NULL ,
  `interval_value` INT(11) NULL DEFAULT NULL ,
  `interval_field` ENUM('YEAR','QUARTER','MONTH','DAY','HOUR','MINUTE','WEEK','SECOND','MICROSECOND','YEAR_MONTH','DAY_HOUR','DAY_MINUTE','DAY_SECOND','HOUR_MINUTE','HOUR_SECOND','MINUTE_SECOND','DAY_MICROSECOND','HOUR_MICROSECOND','MINUTE_MICROSECOND','SECOND_MICROSECOND') NULL DEFAULT NULL ,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  `modified` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `last_executed` DATETIME NULL DEFAULT NULL ,
  `starts` DATETIME NULL DEFAULT NULL ,
  `ends` DATETIME NULL DEFAULT NULL ,
  `status` ENUM('ENABLED','DISABLED','SLAVESIDE_DISABLED') NOT NULL DEFAULT 'ENABLED' ,
  `on_completion` ENUM('DROP','PRESERVE') NOT NULL DEFAULT 'DROP' ,
  `sql_mode` SET('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','NOT_USED','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NO_AUTO_CREATE_USER','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH') NOT NULL DEFAULT '' ,
  `comment` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `originator` INT(10) UNSIGNED NOT NULL ,
  `time_zone` CHAR(64) CHARACTER SET 'latin1' NOT NULL DEFAULT 'SYSTEM' ,
  `character_set_client` CHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL ,
  `collation_connection` CHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL ,
  `db_collation` CHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL ,
  `body_utf8` LONGBLOB NULL DEFAULT NULL ,
  PRIMARY KEY (`db`, `name`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Events';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`func`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`func` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`func` (
  `name` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `ret` TINYINT(1) NOT NULL DEFAULT '0' ,
  `dl` CHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `type` ENUM('function','aggregate') CHARACTER SET 'utf8' NOT NULL ,
  PRIMARY KEY (`name`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'User defined functions';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`general_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`general_log` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`general_log` (
  `event_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  `user_host` MEDIUMTEXT NOT NULL ,
  `thread_id` INT(11) NOT NULL ,
  `server_id` INT(10) UNSIGNED NOT NULL ,
  `command_type` VARCHAR(64) NOT NULL ,
  `argument` MEDIUMTEXT NOT NULL )
ENGINE = CSV
DEFAULT CHARACTER SET = utf8
COMMENT = 'General log';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`help_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`help_category` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`help_category` (
  `help_category_id` SMALLINT(5) UNSIGNED NOT NULL ,
  `name` CHAR(64) NOT NULL ,
  `parent_category_id` SMALLINT(5) UNSIGNED NULL DEFAULT NULL ,
  `url` CHAR(128) NOT NULL ,
  PRIMARY KEY (`help_category_id`) ,
  UNIQUE INDEX `name` (`name` ASC) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'help categories';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`help_keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`help_keyword` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`help_keyword` (
  `help_keyword_id` INT(10) UNSIGNED NOT NULL ,
  `name` CHAR(64) NOT NULL ,
  PRIMARY KEY (`help_keyword_id`) ,
  UNIQUE INDEX `name` (`name` ASC) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'help keywords';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`help_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`help_relation` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`help_relation` (
  `help_topic_id` INT(10) UNSIGNED NOT NULL ,
  `help_keyword_id` INT(10) UNSIGNED NOT NULL ,
  PRIMARY KEY (`help_keyword_id`, `help_topic_id`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'keyword-topic relation';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`help_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`help_topic` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`help_topic` (
  `help_topic_id` INT(10) UNSIGNED NOT NULL ,
  `name` CHAR(64) NOT NULL ,
  `help_category_id` SMALLINT(5) UNSIGNED NOT NULL ,
  `description` TEXT NOT NULL ,
  `example` TEXT NOT NULL ,
  `url` CHAR(128) NOT NULL ,
  PRIMARY KEY (`help_topic_id`) ,
  UNIQUE INDEX `name` (`name` ASC) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'help topics';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`host`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`host` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`host` (
  `Host` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Select_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Insert_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Update_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Delete_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Drop_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Grant_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `References_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Index_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Alter_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_tmp_table_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Lock_tables_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_view_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Show_view_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_routine_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Alter_routine_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Execute_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Trigger_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  PRIMARY KEY (`Host`, `Db`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Host privileges;  Merged with database privileges';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`ndb_binlog_index`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`ndb_binlog_index` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`ndb_binlog_index` (
  `Position` BIGINT(20) UNSIGNED NOT NULL ,
  `File` VARCHAR(255) NOT NULL ,
  `epoch` BIGINT(20) UNSIGNED NOT NULL ,
  `inserts` BIGINT(20) UNSIGNED NOT NULL ,
  `updates` BIGINT(20) UNSIGNED NOT NULL ,
  `deletes` BIGINT(20) UNSIGNED NOT NULL ,
  `schemaops` BIGINT(20) UNSIGNED NOT NULL ,
  PRIMARY KEY (`epoch`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`plugin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`plugin` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`plugin` (
  `name` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `dl` CHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  PRIMARY KEY (`name`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'MySQL plugins';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`proc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`proc` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`proc` (
  `db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `name` CHAR(64) NOT NULL DEFAULT '' ,
  `type` ENUM('FUNCTION','PROCEDURE') NOT NULL ,
  `specific_name` CHAR(64) NOT NULL DEFAULT '' ,
  `language` ENUM('SQL') NOT NULL DEFAULT 'SQL' ,
  `sql_data_access` ENUM('CONTAINS_SQL','NO_SQL','READS_SQL_DATA','MODIFIES_SQL_DATA') NOT NULL DEFAULT 'CONTAINS_SQL' ,
  `is_deterministic` ENUM('YES','NO') NOT NULL DEFAULT 'NO' ,
  `security_type` ENUM('INVOKER','DEFINER') NOT NULL DEFAULT 'DEFINER' ,
  `param_list` BLOB NOT NULL ,
  `returns` LONGBLOB NOT NULL ,
  `body` LONGBLOB NOT NULL ,
  `definer` CHAR(77) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  `modified` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `sql_mode` SET('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','NOT_USED','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NO_AUTO_CREATE_USER','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH') NOT NULL DEFAULT '' ,
  `comment` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `character_set_client` CHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL ,
  `collation_connection` CHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL ,
  `db_collation` CHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL ,
  `body_utf8` LONGBLOB NULL DEFAULT NULL ,
  PRIMARY KEY (`db`, `name`, `type`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Stored Procedures';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`procs_priv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`procs_priv` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`procs_priv` (
  `Host` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `User` CHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Routine_name` CHAR(64) CHARACTER SET 'utf8' NOT NULL DEFAULT '' ,
  `Routine_type` ENUM('FUNCTION','PROCEDURE') CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL ,
  `Grantor` CHAR(77) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Proc_priv` SET('Execute','Alter Routine','Grant') NOT NULL DEFAULT '' ,
  `Timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  PRIMARY KEY (`Host`, `Db`, `User`, `Routine_name`, `Routine_type`) ,
  INDEX `Grantor` (`Grantor` ASC) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Procedure privileges';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`servers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`servers` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`servers` (
  `Server_name` CHAR(64) NOT NULL DEFAULT '' ,
  `Host` CHAR(64) NOT NULL DEFAULT '' ,
  `Db` CHAR(64) NOT NULL DEFAULT '' ,
  `Username` CHAR(64) NOT NULL DEFAULT '' ,
  `Password` CHAR(64) NOT NULL DEFAULT '' ,
  `Port` INT(4) NOT NULL DEFAULT '0' ,
  `Socket` CHAR(64) NOT NULL DEFAULT '' ,
  `Wrapper` CHAR(64) NOT NULL DEFAULT '' ,
  `Owner` CHAR(64) NOT NULL DEFAULT '' ,
  PRIMARY KEY (`Server_name`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'MySQL Foreign Servers table';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`slow_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`slow_log` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`slow_log` (
  `start_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  `user_host` MEDIUMTEXT NOT NULL ,
  `query_time` TIME NOT NULL ,
  `lock_time` TIME NOT NULL ,
  `rows_sent` INT(11) NOT NULL ,
  `rows_examined` INT(11) NOT NULL ,
  `db` VARCHAR(512) NOT NULL ,
  `last_insert_id` INT(11) NOT NULL ,
  `insert_id` INT(11) NOT NULL ,
  `server_id` INT(10) UNSIGNED NOT NULL ,
  `sql_text` MEDIUMTEXT NOT NULL )
ENGINE = CSV
DEFAULT CHARACTER SET = utf8
COMMENT = 'Slow log';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`tables_priv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`tables_priv` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`tables_priv` (
  `Host` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `User` CHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Table_name` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Grantor` CHAR(77) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  `Table_priv` SET('Select','Insert','Update','Delete','Create','Drop','Grant','References','Index','Alter','Create View','Show view','Trigger') NOT NULL DEFAULT '' ,
  `Column_priv` SET('Select','Insert','Update','References') NOT NULL DEFAULT '' ,
  PRIMARY KEY (`Host`, `Db`, `User`, `Table_name`) ,
  INDEX `Grantor` (`Grantor` ASC) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Table privileges';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`time_zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`time_zone` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`time_zone` (
  `Time_zone_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `Use_leap_seconds` ENUM('Y','N') NOT NULL DEFAULT 'N' ,
  PRIMARY KEY (`Time_zone_id`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Time zones';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`time_zone_leap_second`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`time_zone_leap_second` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`time_zone_leap_second` (
  `Transition_time` BIGINT(20) NOT NULL ,
  `Correction` INT(11) NOT NULL ,
  PRIMARY KEY (`Transition_time`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Leap seconds information for time zones';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`time_zone_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`time_zone_name` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`time_zone_name` (
  `Name` CHAR(64) NOT NULL ,
  `Time_zone_id` INT(10) UNSIGNED NOT NULL ,
  PRIMARY KEY (`Name`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Time zone names';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`time_zone_transition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`time_zone_transition` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`time_zone_transition` (
  `Time_zone_id` INT(10) UNSIGNED NOT NULL ,
  `Transition_time` BIGINT(20) NOT NULL ,
  `Transition_type_id` INT(10) UNSIGNED NOT NULL ,
  PRIMARY KEY (`Time_zone_id`, `Transition_time`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Time zone transitions';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`time_zone_transition_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`time_zone_transition_type` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`time_zone_transition_type` (
  `Time_zone_id` INT(10) UNSIGNED NOT NULL ,
  `Transition_type_id` INT(10) UNSIGNED NOT NULL ,
  `Offset` INT(11) NOT NULL DEFAULT '0' ,
  `Is_DST` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
  `Abbreviation` CHAR(8) NOT NULL DEFAULT '' ,
  PRIMARY KEY (`Time_zone_id`, `Transition_type_id`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Time zone transition types';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mysql`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mysql`.`user` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `mysql`.`user` (
  `Host` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `User` CHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '' ,
  `Password` CHAR(41) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL DEFAULT '' ,
  `Select_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Insert_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Update_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Delete_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Drop_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Reload_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Shutdown_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Process_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `File_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Grant_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `References_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Index_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Alter_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Show_db_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Super_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_tmp_table_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Lock_tables_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Execute_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Repl_slave_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Repl_client_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_view_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Show_view_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_routine_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Alter_routine_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Create_user_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Event_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `Trigger_priv` ENUM('N','Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N' ,
  `ssl_type` ENUM('','ANY','X509','SPECIFIED') CHARACTER SET 'utf8' NOT NULL DEFAULT '' ,
  `ssl_cipher` BLOB NOT NULL ,
  `x509_issuer` BLOB NOT NULL ,
  `x509_subject` BLOB NOT NULL ,
  `max_questions` INT(11) UNSIGNED NOT NULL DEFAULT '0' ,
  `max_updates` INT(11) UNSIGNED NOT NULL DEFAULT '0' ,
  `max_connections` INT(11) UNSIGNED NOT NULL DEFAULT '0' ,
  `max_user_connections` INT(11) UNSIGNED NOT NULL DEFAULT '0' ,
  PRIMARY KEY (`Host`, `User`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Users and global privileges';

SHOW WARNINGS;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
